name: Mirror to Personal Repo

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Mirror push to personal repo
        run: |
          git clone --mirror https://github.com/celte-team/celte-landing-page.git repo.git
          cd repo.git
          git remote set-url --push origin https://x-access-token:${{ secrets.MIRROR_PAT }}@github.com/ClementToni/celte-system-mirror.git
          git push --mirror