# .github/workflows/mirror.yml
name: Mirror to Personal Repo

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to Mirror Repo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          # Construct the URL with the PAT for authentication
          MIRROR_URL="https://${{ secrets.MIRROR_PAT }}@github.com/ClementToni/celte-system-mirror.git"

          # Add the remote and push
          git remote add mirror "$MIRROR_URL"
          git push --mirror mirror