# .github/workflows/mirror.yml
name: Mirror to Personal Repo

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Push to Mirror Repo
        run: |
          git remote add mirror ${{ secrets.MIRROR_REPO_URL }}
          git push --mirror mirror
        env:
          GIT_AUTHOR_NAME: github-actions
          GIT_AUTHOR_EMAIL: github-actions@github.com